### ISSUE TITLE
where source code???

### ISSUE THREAD

**Issue by Blakeando** [dumdirt/onani#1]
i rly want to see this code pls sir show me the code i wish to take this code and use it as my own

**Comment by mrpodato** [comment]
`print("onani")`

**Comment by mrpodato** [comment]
LOSER

**Comment by Blakeando** [comment]
sorry i do not know how to use "print" pls show me

**Comment by mrpodato** [comment]
NIG

**Comment by dumdirt** [comment]
sir when you delete the sys32 file it give print screen sir do sys32 delte and it will show

**Comment by mrpodato** [comment]
SHUT UP

**Comment by Blakeando** [comment]
sys32 delete how???

**Comment by dumdirt** [comment]
> sys32 delete how???

stick cock in freezer

**Comment by Blakeando** [comment]
i do not understand

**Comment by mrpodato** [comment]
> > sys32 delete how???
> 
> stick cock in freezer

MY COCK AAAAAAAAAAAAAAAAA

**Comment by dumdirt** [comment]
@ @ @ @ @ @ @ @ @ @ @github

**Comment by mrpodato** [comment]
FUCK IT HURTS

**Comment by mrpodato** [comment]
HELP AAAAAAAAAAAAA

**Comment by dumdirt** [comment]
THE WOLVES ATE MY CUKC

**Comment by mrpodato** [comment]
> THE WOLVES ATE MY CUKC

it was me

**Comment by Blakeando** [comment]
[https://i.imgur.com/XS4UUVb.png](url)

**Comment by Blakeando** [comment]
i need help pls this has not solved my issue

**Comment by mrpodato** [comment]
### MY DICK FELL OFF###

**Comment by dumdirt** [comment]
die

**Comment by Blakeando** [comment]
pls

**Comment by mrpodato** [comment]
- DIE

- SEX

**Comment by Mattlau04** [comment]
Hot
